### ISSUE TITLE
i can't not create certificate in last version of docker-flow-proxy

### ISSUE THREAD

**Issue by codati** [hamburml/docker-flow-letsencrypt#14]
hi,
i can't not create certificate in last version of docker-flow-proxy
what has changed in haproxy config:
```
acl domain_myservice hdr_dom(host) -i domaine.com
```
to
```
acl domain_myservice hdr(host) -i domaine.com
```

if rule of docker-flow-proxy-letsencrypt after rule for service
the rule of service match first for domaine.com/.well-known/acme-challenge/XXX

Quick fixe:
rename docker service docker-flow-proxy-letsencrypt to 10_docker-flow-proxy-letsencrypt 
(rule in haproxy are sort in alphabetical)

**Comment by mhabegger** [comment]
@codati can you post the configuration and labels you have for your main service ?
Since https://github.com/vfarcic/docker-flow-proxy/issues/151 docker-flow-proxy should put the `/` path automatically to the end of the list. Thus would make DFLE come before your actual service.

**Comment by vfarcic** [comment]
I just made another release that simplifies it even more. If a service path starts with `/.well-known`, it'll be placed at the top of the list of ACLs.

https://github.com/vfarcic/docker-flow-proxy/releases/tag/1.234

**Comment by codati** [comment]
vfarcic/docker-flow-proxy:latest is not update?
It works with the vfarcic/docker-flow-proxy:1.237
thanks

**Comment by vfarcic** [comment]
I made a mistake in my .travis file. Now it's corrected. You should be able to pull the latest.

**Comment by codati** [comment]
thanks
