### ISSUE TITLE
Tag each Docker image release

### ISSUE THREAD

**Issue by vfarcic** [hamburml/docker-flow-letsencrypt#2]
It would be nice if each release would be tagged (e.g. v1.0, v1.1, etc). That way it would be easier to update the service.

**Comment by hamburml** [comment]
Yes, I will do that. I also want to provide release logs.

**Comment by hamburml** [comment]
[v0.1.1](https://github.com/hamburml/docker-flow-letsencrypt/releases/tag/v0.1.1)

👍
