### ISSUE TITLE
Document required labels for service contianers to be provisioned.

### ISSUE THREAD

**Issue by Routhinator** [hamburml/docker-flow-letsencrypt#23]
I see that there is a way to manually define hostnames in the config of the letsencrypt container itself, but I cannot determine what labels are required on an service container for automatic configuration of a new host certificate in the docs or elsewhere.

Can you document this please?

**Comment by hamburml** [comment]
I am sorry to say this but I don't fully understand your request.

You want to define hostnames for the letsencrypt container? Do you mean a dns resolution for your services inside the docker network? That should work out of the box, when two services are connected to the same docker network the services can reach each other with their service name.

Or do you want to know how you can say to the running DFLE Service "hey buddy, please try to create another cert for <domain> and send it to the DFP, thanks!".

To be honest, I think you mean the latter, but I just want to be sure. If so, you simply need to stop DFLE, recreate it and add the DOMAIN. The certificates of the other domains were sent to DFP in the past and are therefore stored by it.

**Comment by Routhinator** [comment]
Yeah I was actually thinking this container worked like other containers where I could define the LE domain with a label on the sevice container and not have to update this container every time. This container is an infrastructure container and I don't want to have to update an infrastructure container every time a new service is added. I find the way Domains are defined here breaks my desired workflow.

I found nib0r/docker-flow-proxy-letsencrypt however and it works the way I anticipated this one would. So I'm using it for now.

**Comment by hamburml** [comment]
Never thought about adding this to the service container via label. Also I would presume that it could happen often that the letsencrypt limits are reached fairly easy when the service restarts often and the certs aren't stored persistently inside the container. But I have no idea how n1b0r does this.

BTW: You don't need to restart this container every time a new service is added. You just need to restart it when you have a new domain.

Anyway, have fun using DFP :)
