### ISSUE TITLE
debconf: delaying package configuration, since apt-utils is not installed

### ISSUE THREAD

**Issue by basz** [hamburml/docker-flow-letsencrypt#26]
whilst running `/root/renewAndSendToProxy.sh`

This error message shows `debconf: delaying package configuration, since apt-utils is not installed`.

Not sure if it is important...

**Comment by hamburml** [comment]
Thanks for your report.

What version of DFLE are you using?

**Comment by basz** [comment]
hamburml/docker-flow-letsencrypt:latest

```
docker image ls | grep lets
hamburml/docker-flow-letsencrypt        <none>              a21cb2fac65c        3 weeks ago         270MB
```

**Comment by hamburml** [comment]
This happens when certbot is/was updated. Default behavior is that certbot auto-updates itself. I forgot to set this in the renewScript, https://github.com/hamburml/docker-flow-letsencrypt/commit/97908eb3505a246537a67618ac42b5e1b967d753. When everything works I will release a new release.

**Comment by hamburml** [comment]
Certbot should stop auto updating itself :) Plase use 'latest' or https://github.com/hamburml/docker-flow-letsencrypt/releases/tag/v0.1.3
