### ISSUE TITLE
sending too fast?

### ISSUE THREAD

**Issue by basz** [hamburml/docker-flow-letsencrypt#31]
I had one (pdf.bushbaby.nl) domain consistently not being picked up by the proxy. even though the log said it was pushed...

https://gist.github.com/basz/c110a48f7fdfdeeed051bea77e43efe9

would it be an idea to do a sleep of 0.5 sec in the main loop that sends certs to the proxy?

ps. not sure if this is an issue with this repo or DFP, I'll post there too

**Comment by hamburml** [comment]
Thanks for the issue. Problem was that a variable wasn't reset and when lots of certificates are transferred to the server the script thoughts everything was all right. Should be fixed when using 'latest' or https://github.com/hamburml/docker-flow-letsencrypt/releases/tag/v0.1.3

**Comment by basz** [comment]
great thanks!
