### ISSUE TITLE
Sent known certs before renewal

### ISSUE THREAD

**Issue by basz** [hamburml/docker-flow-letsencrypt#32]
idea: the renewAndSent script could be improved by immediately sending any known certificates before doing a renewal round. The renewal step can take a while if you have many certificates even when none need refreshing. Removing the stack and deploying it again becomes slowish because proxy is informed late...

**Comment by hamburml** [comment]
Thanks for the issue.
Normally you don't remove the stack which handles proxy and certificates often but you are right, it's a great idea to send the known certificates at the beginning AND when the renewal round is finished. 
If the certificates would be transferred as docker secrets we had a bigger problem but that's not the case right now. Will do this today.

**Comment by hamburml** [comment]
Sorry, I had some family issues. Please try the https://hub.docker.com/r/hamburml/docker-flow-letsencrypt/tags/ testing-tag.

**Comment by basz** [comment]
it works. I find the delay of 10 seconds a bit long, whilst sending old certificates, but I presume you have a valid reason for it.

thanks!

**Comment by basz** [comment]
sorry misreading logs. no delay! perfect

**Comment by hamburml** [comment]
Closed by https://github.com/hamburml/docker-flow-letsencrypt/releases/tag/v0.1.4
