### ISSUE TITLE
invalid mount config for type "bind": bind source path does not exist

### ISSUE THREAD

**Issue by ruudboon** [hamburml/docker-flow-letsencrypt#33]
Trying to run letsencrypt in on my stack but having a hard time getting it working.
Currently I'm seeing this error

invalid mount config for type "bind": bind source path does not exist

**Comment by ruudboon** [comment]
Sorry.. Forgot to create the letsencrypt dir... (And found out after 1hr of testing hahaha)

**Comment by hamburml** [comment]
Great to hear. When you have other questions simply ask :)

**Comment by ruudboon** [comment]
I did found an issue with ipv6. My domains already had ipv6 assigned. Looks like letsencrypt use ipv6 as default. Unfortunately it looks like Docker Flow Proxy is not handeling ipv6 yet.
Deleting the ipv6 entries solved the issue.

Thnx for this project!!
