### ISSUE TITLE
Docker Flow Proxy: 503 Service Unavailable for letsencrypt companion

### ISSUE THREAD

**Issue by aleskinen** [hamburml/docker-flow-letsencrypt#35]
Proxy version: vfarcic/docker-flow-proxy:17.11.01-52

I have docker.compose like:
version: "3.3"

services:

  # Let's Encrypt Companion
  letsencrypt-companion:
    image: hamburml/docker-flow-letsencrypt:latest
    networks:
      - proxy
    environment:
      - DOMAIN_1=('teknetti.fi')
      - CERTBOT_EMAIL=webmaster@tek.fi
      - PROXY_ADDRESS=proxy
      - CERTBOT_CRON_RENEW=('0 3 * * *' '0 15 * * *')
    volumes:
          - ./letsencrypt:/etc/letsencrypt
    deploy:
      labels:
        - com.df.servicePath=/.well-known/acme-challenge
        - com.df.notify=true
        - com.df.distribute=true
        - com.df.port=80
      placement:
        constraints: [node.hostname == dcadev.tek.fi]
      replicas: 1

networks:
  proxy:
    external: true

In proxy logs I have:
core_proxy.1.7zxs4ean82nq@dcadev.tek.fi    | 2017/11/20 10:15:11 Sending distribution request to http://10.0.1.3:8080/v1/docker-flow-proxy/reconfigure?distribute=false&port=80&replicas=1&serviceName=core_letsencrypt-companion&servicePath=%2F.well-known%2Facme-challenge
core_proxy.1.7zxs4ean82nq@dcadev.tek.fi    | 2017/11/20 10:15:11 Creating configuration for the service core_letsencrypt-companion
core_proxy.1.7zxs4ean82nq@dcadev.tek.fi    | 2017/11/20 10:15:11 Reloading the proxy
core_proxy.1.7zxs4ean82nq@dcadev.tek.fi    | 2017/11/20 10:15:11 Validating configuration
core_proxy.1.7zxs4ean82nq@dcadev.tek.fi    | 2017/11/20 10:15:11 Proxy config was reloaded

in letsencrypt companion loga I have:
core_letsencrypt-companion.1.rdoecghqyc4r@dcadev.tek.fi    | Starting Docker Flow: Let's Encrypt
core_letsencrypt-companion.1.rdoecghqyc4r@dcadev.tek.fi    | Docker Flow: Let's Encrypt started
core_letsencrypt-companion.1.rdoecghqyc4r@dcadev.tek.fi    | We will use webmaster@tek.fi for certificate registration with certbot. This e-mail is used by Let's Encrypt when you lose the account and want to get it back.
core_letsencrypt-companion.1.rdoecghqyc4r@dcadev.tek.fi    | Saving debug log to /var/log/letsencrypt/letsencrypt.log
core_letsencrypt-companion.1.rdoecghqyc4r@dcadev.tek.fi    | Plugins selected: Authenticator standalone, Installer None
core_letsencrypt-companion.1.rdoecghqyc4r@dcadev.tek.fi    | Obtaining a new certificate
core_letsencrypt-companion.1.rdoecghqyc4r@dcadev.tek.fi    | Performing the following challenges:
core_letsencrypt-companion.1.rdoecghqyc4r@dcadev.tek.fi    | http-01 challenge for teknetti.fi
core_letsencrypt-companion.1.rdoecghqyc4r@dcadev.tek.fi    | Waiting for verification...
core_letsencrypt-companion.1.rdoecghqyc4r@dcadev.tek.fi    | Cleaning up challenges
core_letsencrypt-companion.1.rdoecghqyc4r@dcadev.tek.fi    | Failed authorization procedure. teknetti.fi (http-01): urn:acme:error:connection :: The server could not connect to the client to verify the domain :: Fetching http://teknetti.fi/.well-known/acme-challenge/8OEj8St3aKJMwf5hhEEediJglQdxatP1hkKWdGdAeck: Timeout

and if I'll try with browser I get:
Docker Flow Proxy: 503 Service Unavailable.

If I go to container:
# curl localhost:80
curl: (7) Failed to connect to localhost port 80: Connection refused
ps aux 
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root         1  0.0  0.0  18036  2796 ?        Ss   10:15   0:00 /bin/bash /root/servicestart
root       174  0.0  0.5  47168 17604 ?        S    10:16   0:00 /usr/bin/python /usr/bin/supervisord -c /etc/supervisor/conf.d/supervi
root       177  0.0  0.0  26068  2560 ?        S    10:16   0:00 cron -f -L 15 > /var/log/dockeroutput.log

Where I can search the problem?

Thank you for any help.

**Comment by hamburml** [comment]
Hello aleskinen,

your Docker Flow Proxy logs show that the config is created and the proxy is reloaded.

The Docker Flow Letsencrypt logs show that certbot (the tool which is used to start the letsencrypt authentication process) can't reach your server (timeout is happening). This normally means that a letsencrypt-server can't reach your server where DFP runs.

You mentioned that when you try it with a browser you get `Docker Flow Proxy: 503 Service Unavailable.`. Have you tried this on the same machine? Maybe the port 80 isn't forwarded and therefore it works when you open your browser on the same machine. When I try to reach your domain teknetti.fi I also get a `connection_timed_out` error.

Hope this helps.

**Comment by aleskinen** [comment]
These both are running in same host in swarm stack mode.
Terveisin,

Arto Leskinen
IT-asiantuntija
arto.leskinen@tek.fi
+358 40 553 9474
TEKNIIKAN AKATEEMISET TEK
Ratavartijankatu 2, 00520 Helsinki
www.tek.fi<http://www.tek.fi/> | @TEK_akateemiset

**Comment by hamburml** [comment]
They can run on the same host, that doesn't matter. The domain `teknetti.fi` can't be reached from the www, therefore the letsencrypt-servers can't reach the DFL-Container. For example when I try to reach `teknetti.fi` my browser doesn't show me the `Docker Flow Proxy: 503 Service Unavailable` message, I get an `ERR_CONNECTION_TIMED_OUT` message. When I try to ping your domain, the following is happening

```
ping teknetti.fi
PING teknetti.fi (194.100.213.88) 56(84) bytes of data.
^C
--- teknetti.fi ping statistics ---
35 packets transmitted, 0 received, 100% packet loss, time 34786ms
```

Are you sure that the host can be reached from outside your network? Maybe @vfarcic has an idea why your proxy can't be reached.

*edit*

Looks like something changed?
I can reach your server and the https certificate is working 👍 Great!

**Comment by aleskinen** [comment]
You were right, this was new dev server I used for testing and I did not have opened traffic from firewall.
Does not answer even from inside the container if it does not have cert created? This was what confused me.

Thanks!

**Comment by hamburml** [comment]
I am not quite sure but I think certbot does not answer on plain simple HTTP-requests. Therefore the curl localhost:80 failed. Please remember that letsencrypt has rate limits and you should store the letsencrypt-files on the docker host and not only inside the container. If everything works like you want it you can close the issue.

Thanks for using DFL 👍
