### ISSUE TITLE
Method not allowed

### ISSUE THREAD

**Issue by basz** [hamburml/docker-flow-letsencrypt#48]
Hi,

I'm getting "The request message was malformed :: Method not allowed' in the logs.". Looking at this [thread](https://community.letsencrypt.org/t/problem-with-renew-certificates-the-request-message-was-malformed-method-not-allowed/107889/10) they seem to suggest we need a newer certbot version. 

Are you able to release a new version on short notice?

**Comment by hamburml** [comment]
I triggered a new latest build. Let's see if everything still works.

**Comment by hamburml** [comment]
I am curious: Are you still using docker swarm and docker flow? :D

**Comment by hamburml** [comment]
Done. Latest tag should be certbot 1.0.0. https://hub.docker.com/r/hamburml/docker-flow-letsencrypt/tags

Please give a short reply if it's still working.

**Comment by basz** [comment]
Yes, still am for a small swarm. No time to get familiar with k8s yet. But should do that sooner that later i guess.

*latest* seems to get certs 👍 

Big Thank You!
