### ISSUE TITLE
Request certs

### ISSUE THREAD

**Issue by vfarcic** [hamburml/docker-flow-letsencrypt#7]
Please implement a feature that will allow generation of certs on demand. That way, if a proxy fails and is rescheduled, it could request certs during initialization.

**Comment by hamburml** [comment]
When curling `http://letsencrypt-companion/request-certs` (or whatever you called the service) https://github.com/hamburml/docker-flow-letsencrypt/blob/master/renewAndSendToProxy.sh is executed. Currently I added this to the testing branch. Could you please try it out?

**Comment by hamburml** [comment]
Docker Secrets should make this unnecessary. `http://letsencrypt-companion/request-certs` will stay.
